# v3 syntax
version: "3"

# Named volumes
volumes:
  # MySQL Data
  library-db-data:
    driver: local

services:
  # MySQL (5.7)
  db:
    image: mysql:5.7
    container_name: library-db
    volumes:
      - library-db-data:/var/lib/mysql
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=library
      - MYSQL_DATABASE=library
      - MYSQL_USER=library
      - MYSQL_PASSWORD=library
  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: library-app
    depends_on:
      - db
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - db
